### ISSUE TITLE
Vector<> have different types   —— XIAOMI MI_8 Android 9 (sdk 28) 

### ISSUE THREAD

**Issue by arckalsun** [DeviceFarmer/minicap#2]
$ adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1440x2560@1440x2560/0 -t
PID: 2479
INFO: Using projection 1440x2560@1440x2560/0
INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options
INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display
Vector<> have different types (this=0x7fc7d7f700, rhs=0x7fc7d7f820)
Aborted

I alse have this problem, but there is no problem at beginning, after some days it happened, the devices is XIAOMI MI_8 Android 9 (sdk 28)

**Comment by Maciejszuchta** [comment]
Same Problem here on :
```
Device name: Mi9SE
Manufacturer: Xiaomi
Model: Mi 9 SE
System: N/A ver. 4.9.186-perf-ge61ced4
CPU: Inc SDM712 - arm64-v8a
CPU Cores: 8
GPU: Qualcomm Adreno (TM) 616 OpenGL E(...)
Motherboard: sdm710
Storage: 224.85 GB
Screen size: 2340 x 1080
Screen density: 480 / -1
Total RAM: 5753.69 MB
Used space: 34.32/224.85 GB
```

Running 
```
adb -s 317dcad4 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1080x2340@1080x2340/0
PID: 12107
INFO: Using projection 1080x2340@1080x2340/0
INFO: (external/MY_minicap/src/minicap_29.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_29.cpp:244) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_29.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_29.cpp:261) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_29.cpp:264) Setting buffer options
INFO: (external/MY_minicap/src/minicap_29.cpp:268) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_29.cpp:272) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_29.cpp:276) Publishing virtual display
Vector<> have different types (this=0x7fe2f4c640, rhs=0x7fe2f4c790)
Aborted
```

**Comment by s2339956** [comment]
Infinite loop
---------------------------------------------
Manual installation of STFService.apk remains the same
MIUI: 11.0.6
AndroidOS: 9
---------------------------------------------
stf_1        | 2020-07-23T05:35:24.245Z IMP/device:plugins:group 240 [1291d4df] Now owned by "s2339956@gmail.com"
stf_1        | 2020-07-23T05:35:24.247Z INF/device:plugins:group 240 [1291d4df] Subscribing to group channel "84lE13ejTSepiHnmQ4bavg=="
stf_1        | 2020-07-23T05:35:24.553Z INF/device:plugins:screen:stream 240 [1291d4df] Setting frame producer projection to 753x1175
stf_1        | 2020-07-23T05:35:24.556Z INF/device:plugins:screen:stream 240 [1291d4df] Requesting frame producer to start
stf_1        | 2020-07-23T05:35:24.558Z INF/device:plugins:screen:stream 240 [1291d4df] Launching screen service
stf_1        | 2020-07-23T05:35:24.648Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "PID: 13485"
stf_1        | 2020-07-23T05:35:24.649Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: Using projection 1080x2340@542x1175/0"
stf_1        | 2020-07-23T05:35:24.651Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient"
stf_1        | 2020-07-23T05:35:24.653Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check"
stf_1        | 2020-07-23T05:35:24.656Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display"
stf_1        | 2020-07-23T05:35:24.658Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue"
stf_1        | 2020-07-23T05:35:24.660Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options"
stf_1        | 2020-07-23T05:35:24.666Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer"
stf_1        | 2020-07-23T05:35:24.669Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter"
stf_1        | 2020-07-23T05:35:24.671Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display"
stf_1        | 2020-07-23T05:35:24.673Z INF/device:plugins:screen:stream 240 [1291d4df] minicap says: "Vector<> have different types (this=0x7ff7fc1c80, rhs=0x7ff7fc1da0)"
stf_1        | 2020-07-23T05:35:24.675Z INF/device:plugins:screen:stream 240 [1291d4df] Connecting to minicap service
stf_1        | 2020-07-23T05:35:24.754Z WRN/device:plugins:screen:stream 240 [1291d4df] Shell keeping minicap running ended unexpectedly
stf_1        | 2020-07-23T05:35:25.124Z INF/device:plugins:connect 240 [1291d4df] Listening on port 7433
stf_1        | 2020-07-23T05:35:25.131Z IMP/device:plugins:connect 240 [1291d4df] Remote Connect Started for device "1291d4df" at "202.39.9.120:7433"
stf_1        | 2020-07-23T05:35:26.239Z INF/device:plugins:screen:stream 240 [1291d4df] Disconnecting from minicap service
stf_1        | 2020-07-23T05:35:26.241Z INF/device:plugins:screen:stream 240 [1291d4df] Stopping minicap service
stf_1        | 2020-07-23T05:35:26.243Z FTL/device:plugins:screen:stream 240 [1291d4df] Frame producer had an error FailError: Failure: 'closed'
stf_1        |     at /app/node_modules/@devicefarmer/adbkit/lib/adb/parser.js:183:29
stf_1        |     at runCallback (timers.js:789:20)
stf_1        |     at tryOnImmediate (timers.js:751:5)
stf_1        |     at processImmediate [as _immediateCallback] (timers.js:722:5)
stf_1        | 2020-07-23T05:35:26.244Z FTL/util:lifecycle 240 [1291d4df] Shutting down due to fatal error
stf_1        | 2020-07-23T05:35:26.251Z INF/provider 44 [*] Cleaning up device worker "1291d4df"
stf_1        | 2020-07-23T05:35:26.252Z ERR/provider 44 [*] Device worker "1291d4df" died with code 1
stf_1        | 2020-07-23T05:35:26.252Z INF/provider 44 [*] Restarting device worker "1291d4df"
stf_1        | 2020-07-23T05:35:27.243Z INF/device:support:push 252 [1291d4df] Sending output to "tcp://127.0.0.1:7116"
stf_1        | 2020-07-23T05:35:27.248Z INF/device 252 [1291d4df] Preparing device
stf_1        | 2020-07-23T05:35:27.816Z INF/device:support:sub 252 [1291d4df] Receiving input from "tcp://127.0.0.1:7114"
stf_1        | 2020-07-23T05:35:27.817Z INF/device:support:sub 252 [1291d4df] Subscribing to permanent channel "*ALL"
stf_1        | 2020-07-23T05:35:27.907Z INF/device:support:properties 252 [1291d4df] Loading properties
stf_1        | 2020-07-23T05:35:27.984Z INF/device:support:sdk 252 [1291d4df] Supports SDK 28
stf_1        | 2020-07-23T05:35:27.987Z INF/device:support:abi 252 [1291d4df] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
stf_1        | 2020-07-23T05:35:28.232Z INF/device:resources:minicap 252 [1291d4df] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
stf_1        | 2020-07-23T05:35:28.235Z INF/device:resources:minicap 252 [1291d4df] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-28/minicap.so" as "/data/local/tmp/minicap.so"
stf_1        | 2020-07-23T05:35:28.406Z INF/device:resources:service 252 [1291d4df] Checking whether we need to install STFService
stf_1        | 2020-07-23T05:35:28.494Z INF/device:resources:service 252 [1291d4df] Running version check
stf_1        | 2020-07-23T05:35:28.900Z INF/device:resources:service 252 [1291d4df] STFService up to date
stf_1        | 2020-07-23T05:35:28.902Z INF/device:plugins:service 252 [1291d4df] Launching agent
stf_1        | 2020-07-23T05:35:29.608Z INF/device:plugins:service 252 [1291d4df] Agent says: "Listening on @stfagent"
stf_1        | 2020-07-23T05:35:29.638Z INF/device:plugins:service 252 [1291d4df] Launching service
stf_1        | 2020-07-23T05:35:29.641Z INF/device:plugins:service 252 [1291d4df] using 'start-foreground-service' command for API 28
stf_1        | 2020-07-23T05:35:29.646Z INF/device:plugins:service 252 [1291d4df] Agent says: "InputClient started"
stf_1        | 2020-07-23T05:35:29.793Z INF/device:plugins:display 252 [1291d4df] Reading display info
stf_1        | 2020-07-23T05:35:29.845Z INF/device:plugins:phone 252 [1291d4df] Fetching phone info
stf_1        | 2020-07-23T05:35:29.898Z INF/device:plugins:identity 252 [1291d4df] Solving identity
stf_1        | 2020-07-23T05:35:29.926Z INF/device:plugins:solo 252 [1291d4df] Subscribing to permanent channel "+AU4+eTn4OUDnfMucaaUztzTR7k="
stf_1        | 2020-07-23T05:35:29.932Z INF/device:plugins:screen:stream 252 [1291d4df] Starting WebSocket server on port 7436
stf_1        | 2020-07-23T05:35:30.177Z INF/device:resources:minitouch 252 [1291d4df] Installing "/app/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch" as "/data/local/tmp/minitouch"
stf_1        | 2020-07-23T05:35:30.280Z WRN/device:plugins:data 252 [1291d4df] Unable to find device data { serial: '1291d4df',
stf_1        |   platform: 'Android',
stf_1        |   manufacturer: 'XIAOMI',
stf_1        |   operator: ',中國移動',
stf_1        |   model: 'Redmi Note 8',
stf_1        |   version: '9',
stf_1        |   abi: 'arm64-v8a',
stf_1        |   sdk: '28',
stf_1        |   product: 'ginkgo',
stf_1        |   cpuPlatform: 'trinket',
stf_1        |   openGLESVersion: '3.2',
stf_1        |   marketName: 'Redmi Note 8',
stf_1        |   display:
stf_1        |    { id: 0,
stf_1        |      width: 1080,
stf_1        |      height: 2340,
stf_1        |      xdpi: 409.4320068359375,
stf_1        |      ydpi: 409.90301513671875,
stf_1        |      fps: 60.000003814697266,
stf_1        |      density: 2.75,
stf_1        |      rotation: 0,
stf_1        |      secure: true,
stf_1        |      size: 6.288630704837173,
stf_1        |      url: 'ws://202.39.9.120:7436' },
stf_1        |   phone: { network: 'LTE' } }
stf_1        | 2020-07-23T05:35:30.305Z INF/device:plugins:touch 252 [1291d4df] Touch origin is top left
stf_1        | 2020-07-23T05:35:30.307Z INF/device:plugins:touch 252 [1291d4df] Requesting touch consumer to start
stf_1        | 2020-07-23T05:35:30.310Z INF/device:plugins:touch 252 [1291d4df] Launching touch service
stf_1        | 2020-07-23T05:35:30.332Z INF/device:plugins:touch 252 [1291d4df] Connecting to minitouch service
stf_1        | 2020-07-23T05:35:30.372Z INF/device:plugins:touch 252 [1291d4df] minitouch says: "Type B touch device NVTCapacitiveTouchScreen (1079x2339 with 10 contacts) detected on /dev/input/event2 (score 22597)"
stf_1        | 2020-07-23T05:35:30.454Z INF/device:plugins:touch 252 [1291d4df] Reading minitouch banner
stf_1        | 2020-07-23T05:35:30.459Z INF/device:plugins:touch 252 [1291d4df] minitouch says: "Connection established"
stf_1        | 2020-07-23T05:35:30.511Z INF/device:plugins:vnc 252 [1291d4df] Starting VNC server on port 7438
stf_1        | 2020-07-23T05:35:30.519Z INF/device:plugins:browser 252 [1291d4df] Loading browser list
stf_1        | 2020-07-23T05:35:30.554Z INF/device:plugins:browser 252 [1291d4df] Updating browser list
stf_1        | 2020-07-23T05:35:30.562Z INF/device:plugins:mute 252 [1291d4df] Will not mute master volume
stf_1        | 2020-07-23T05:35:30.833Z INF/device:resources:minirev 252 [1291d4df] Installing "/app/vendor/minirev/arm64-v8a/minirev" as "/data/local/tmp/minirev"
stf_1        | 2020-07-23T05:35:30.944Z INF/device:plugins:forward 252 [1291d4df] Launching reverse port forwarding service
stf_1        | 2020-07-23T05:35:30.973Z INF/device:plugins:forward 252 [1291d4df] Connecting to reverse port forwarding service
stf_1        | 2020-07-23T05:35:31.229Z INF/device 252 [1291d4df] Fully operational

------------------------------------------------------------------------------------------

**Comment by JoeJoeYuan** [comment]
I meet the same error! at beginning no problem, but after one day, it can't be used and will show 'someone stole your device'.
stf version: 3.4.1
device: RedMi-8 android-9

below is stf logs:

minicap says: "PID: 27645"
minicap says: "INFO: Using projection 720x1520@382x806/0"
Connecting to minicap service
minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient"
minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check"
minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display"
minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue"
minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options"
minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer"
minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter"
minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display"
minicap says: "Vector<> have different types (this=0x7fffd17df0, rhs=0x7fffd17f10)"
Shell keeping minicap running ended unexpectedly
Disconnecting from minicap service
Stopping minicap service
Frame producer had an error FailError: Failure: 'closed'
    at /app/node_modules/adbkit/lib/adb/parser.js:183:29
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
Shutting down due to fatal error

**Comment by perunf** [comment]
Same Problem here on :
`Device name: RedmiNote7-RedmiNote
Manufacturer: Xiaomi
Model: Redmi Note 7
System: ver. 4.4.153-perf+
CPU: Inc SDM660 - arm64-v8a
CPU Cores: 8
GPU: Qualcomm Adreno (TM) 512 OpenGL ES 3.2 V@331.0 (GIT@c455b9b Ib7912a5d4e)
Motherboard: sdm660
Storage: 106.02 GB
Screen size: 2340 x 1080
Screen density: 440 / -1
Total RAM: 3824.41 MB
Used space: 27.39/106.02 GB`

Running:
`adb -s d30e385 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1080x2340@1080x2340/0
PID: 17234
INFO: Using projection 1080x2340@1080x2340/0
INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options
INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display
Vector<> have different types (this=0x7fe0ebb090, rhs=0x7fe0ebb1b0)
Aborted`

**Comment by varundtsfi** [comment]
For Android 10 It got resolved 

https://github.com/DeviceFarmer/minicap/issues/6#issuecomment-720031787

but for Android 9. It's in progress as I have downloaded the OS yesterday so tonight I will try to build it for android 9 too and Provide a fix.
